name: Ruby

on: [push,pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby-version: [2.7.1, head]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Set up RBS and bundle install
      run: |
        cd rbs && bundle install && bundle exec rake parser && cd ..
        bundle install
    - name: Run the test
      run: |
        bundle exec rake
